### ISSUE TITLE
Bring emfjson/emfjson-jackson to eclipse-emfcloud

### ISSUE THREAD

**Issue by planger** [eclipse-emfcloud/emfcloud#1]
We are very happy that [EMFJson/emfjson-jackson](https://github.com/emfjson/emfjson-jackson) agreed to become part of Eclipse EMF.Cloud! This issue shall track the necessary steps and the progress of this matter:

- [x] Prepare archive for initial contribution
      This bundle must contain all sources with the correct copyright headers for both EPL-2.0, and MIT
- [x] Make sure all contributors of EMFJson signed the [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/eca)
- [x] Open CQ at Eclipse
- [x] Upload archive to the CQ at Eclipse

Once the Eclipse Foundation confirms that this contribution can move forward
- [x] Request github repository from Eclipse
- [x] Nominate @ghillairet for becoming Eclipse EMFCloud committer
- [x] Make initial commit with content of aforementioned archive
- [x] Set up CI and publishing

Before first release
- [x] Initiate release review

For more information, see [Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/).
Thanks @ghillairet for agreeing to bring EMFJson to Eclipse!

**Comment by ghillairet** [comment]
@planger The source headers have been updated with the dual license. I have signed the contributor agreement as well as one of the contributors.

**Comment by planger** [comment]
@ghillairet I think the election for you being a committer is now approved. Welcome to the team! :100: 

So I think we can now proceed and you can open the CQ. If you go to the Eclipse [project page of emf.cloud](https://projects.eclipse.org/projects/ecd.emfcloud) and log in, you should see in the committer tools box at the right side a link that says "Create a Contribution Questionnai" ([direct link to create a CQ](https://projects.eclipse.org/projects/ecd.emfcloud/cq/create)). There you can provide the details to start the IP process for contributing emf.json.

As a reference, you might want to take a look at a [recent contribution questionnaire](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20932) that we opened. Mostly it should be clear: you need to specify the license (EPL-2.0 OR MIT), declare the contributors and upload the zip with the sources to be included in the contribution.

Thanks a lot and please let me know if there are any questions! We'll monitor the CQ once it is opened. Thanks again!

**Comment by ghillairet** [comment]
@planger Thanks. I am not able to access this link https://projects.eclipse.org/projects/ecd.emfcloud/cq/create I am getting an access denied error.

**Comment by planger** [comment]
> @planger Thanks. I am not able to access this link https://projects.eclipse.org/projects/ecd.emfcloud/cq/create I am getting an access denied error.

Hm, this is strange. Any committer if logged in should be able to create a CQ. I added a comment in the [Eclipse bugzilla ticket for EMF.cloud](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549283#c16) and asked for help. Thanks!

**Comment by planger** [comment]
@ghillairet Can you please try again to open the CQ? Wayne from the Eclipse foundation came back to us on our question regarding your access rights and said that it should work now. Thanks!

**Comment by ghillairet** [comment]
@planger I am having a problem with my eclipse account since yesterday, I cannot login anymore, I contacted the webmaster to see what's happening, waiting for answer.

**Comment by ghillairet** [comment]
@planger Opened CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21634

**Comment by planger** [comment]
The CQ is in parallel review state and we have green lights to do the initial commit! \o/
I've requested a github repo: https://bugs.eclipse.org/bugs/show_bug.cgi?id=560403

@ghillairet As soon as this is available, please make the initial commit with the content that you've uploaded in the CQ. Thanks! :)

After that we can start setting up the continuous integration, etc. and move ongoing development to the Eclipse repository.

**Comment by planger** [comment]
Github repo is available: https://github.com/eclipse-emfcloud/emfjson-jackson

**Comment by ghillairet** [comment]
@planger What's the usual way to do it? Do I keep existing git history or should I just upload the zipped sources? I don't mind either ways.

**Comment by planger** [comment]
> @planger What's the usual way to do it? Do I keep existing git history or should I just upload the zipped sources? I don't mind either ways.

Thanks for asking! Please create _one_ initial commit (without history) that reflects exactly the initial contribution uploaded in the CQ. This way, the IP team can better track the changes done in the meantime. Thanks a lot!

**Comment by lucas-koehler** [comment]
@planger can this be closed?

**Comment by planger** [comment]
Yes, thanks for pointing that out. I think it can be closed.
emfjson-jackson has been released: https://github.com/eclipse-emfcloud/emfjson-jackson/releases/tag/v2.0.0
