### ISSUE TITLE
Broken link on web site

### ISSUE THREAD

**Issue by abstratt** [eclipse-emfcloud/emfcloud#3]
See:

https://www.eclipse.org/emfcloud/contact/

The first link for "Join our mailing list" wrongly points to:

https://accounts.eclipse.org/mailing-list/emdcloud-dev

instead of

https://accounts.eclipse.org/mailing-list/emfcloud-dev - as the second one correctly does.

**Comment by eneufeld** [comment]
Thank you for pointing this out. We will fix this asap.

**Comment by eneufeld** [comment]
Should be fixed now.
